apiVersion: v2
name: discord-bot
description: "\U0001F3B5 Music bot for my private Discord server, powered by discord-player"
icon: "data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%2270%2080%20885%201040%22%3E%3Cpath%20d%3D%22M180.5%201120q-48%200-79.5-30c-21-20-31.5-46.83-31.5-80.5q0-44.5%2024.5-81.75t68.5-60%20102-23.75V174.5l690-94.5v766q0%2088-45%20140.75c-30%2035.17-69.667%2052.75-119%2052.75q-48%200-79.5-30T679.5%20929q0-44.5%2024.5-81.75t68.5-60%20102-23.75V303l-530%2072.5v551c0%2058.667-15%20105.58-45%20140.75s-69.667%2052.75-119%2052.75%22%2F%3E%3C%2Fsvg%3E"
home: https://github.com/xxczaki/discord-bot
keywords:
  - discord-bot
  - discord-music-bot
  - discord
maintainers:
  - name: Antoni Kępiński
    url: https://github.com/xxczaki
sources:
  - https://github.com/xxczaki/discord-bot/tree/main/helm/discord-bot
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.3
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 957465db204c0a906df99ce10c1d9910510e8795
dependencies:
  - name: redis
    version: ~20.6.3
    repository: https://charts.bitnami.com/bitnami
annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/signKey: |
    fingerprint: 9C365333A7EBFC6AED1A0B2B28C62A078051AE35
    url: https://xxczaki.github.io/discord-bot/key.asc
